--- #YAML:1.0
name:                Rose-DB
version:             0.740
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Bit::Vector::Overload:         6.4
    Clone::PP:                     0
    DateTime::Duration:            0
    DateTime::Format::MySQL:       0
    DateTime::Format::Pg:          0.11
    DBI:                           0
    Rose::DateTime::Util:          0.532
    Rose::Object:                  0.82
    Scalar::Util:                  0
    SQL::ReservedWords:            0
    Test::More:                    0
    Time::Clock:                   0
    YAML::Syck:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
