# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rose-DB
version:      0.722
version_from: lib/Rose/DB.pm
installdirs:  site
requires:
    Bit::Vector::Overload:         6.4
    DateTime::Duration:            0
    DateTime::Format::MySQL:       0
    DateTime::Format::Pg:          0.11
    DBI:                           0
    Rose::DateTime::Util:          0.52
    Rose::Object:                  0
    Test::More:                    0
    Time::Clock:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
